version: '2'

services:
  jupiter-notebook:
    build: './jupiter-notebook/'
    # image: jupyter/pyspark-notebook
    restart: always
    container_name: jupiter-notebook
    # user: root
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      - PASSWORD=my-password
      - JUPYTER_TOKEN=easy
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/opt/bitnami/spark/temp:ro
  
  spark:
    image: docker.io/bitnami/spark:3.0.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./books:/home/books
      - ./data:/opt/bitnami/spark/temp:ro

  spark-worker:
    image: docker.io/bitnami/spark:3.0.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    # ports:
    #   - '8081:8081'
    volumes:
      - ./data:/opt/bitnami/spark/temp:ro
